// Standardtekster. Én formulering, dansk som et menneske taler.
// Ny flade: importer herfra. Skriv ikke en ottende variant.

export const TEKST = {
  tomListe: "Ingen sager endnu.",
  tomAktivitet: "Ingen hændelser.",
  mangler: "mangler",
  manglerN: (a, b) => `${a} af ${b} mangler`,
  gem: "Gem",
  gemt: "Gemt.",
  ukendt: "ukendt",
  streg: "—",
  ingenAdgang: "Ingen adgang",
  ingenAdgangH1: "Den her side kræver, at du er logget ind som menneske.",
  ingenAdgangLead: "Servicetokens kan læse, men ikke godkende eller indsende. Det er med vilje: en maskine må ikke stå som den, der traf beslutningen.",
  fejl: "Fejl",
  fejlH1: "Handlingen blev ikke gennemført.",
  fejlLead: "Intet er markeret som godkendt eller indsendt på et forkert grundlag.",
  ingenBeslutning: "Ingen beslutning endnu.",
  kanIkkeIndsende: "Kan først registreres, når en gældende godkendelse ligger på den aktuelle pakke.",
  internFod: (navn) => `Intern side · bag login · ${navn}`,
  internNote: "Tal og status her er arbejdsgrundlag, ikke et regnskab. Kilde og dato står ved hver post.",

  logUd: "Log ud",
  tilForsiden: "← Offentlig side",
  mitFod: (navn) => `Fællesskabet · ${navn}`,
  mitFodGaest: "Fællesskabet · et link i mailen, så er du inde",
  mitNote: "Linket virker i et kvarter, og kun i den browser du bad om det fra.",
  mitSvar: "Hvis adressen hører til nogen her, ligger der en mail nu.",
  mitLoginH1: "Et link, så er du inde.",
  mitLoginLead: "Skriv den mail, vi kender dig på. Vi sender et link. Ingen adgangskode.",
  mitKnap: "Send mig et link",
  mitMailLabel: "Din mail",
  mitIndeLead: "Der kommer mere, når det er bygget. Indtil da er det nok at være inde.",
  mitLinkBrugt: "Det link er allerede brugt. Bed om et nyt.",
  mitLinkGammelt: "Det link er for gammelt. Bed om et nyt.",
  mitLinkAndenBrowser: "Det link hører til en anden browser. Åbn det dér, hvor du bad om det.",
  mitLinkUgyldigt: "Det link virker ikke. Bed om et nyt.",
  mitPasskeyTilbud: "Skal den her enhed huske dig? Så er du inde næste gang uden at tjekke mail.",
  mitPasskeyJa: "Ja, husk den",
  mitPasskeyNej: "Nej tak — spørg ikke igen",
  mitPasskeyIgang: "Browseren spørger nu, om den må huske dig. Det tager et øjeblik.",
  mitPasskeyFejl: "Det lykkedes ikke at huske enheden. Du er stadig inde — prøv igen næste gang, eller lad være. Magic link virker uanset.",
  mitSessionMangler: "Login er ikke sat op endnu (SESSION_NOEGLE mangler). Sig det til den, der driver siden.",
};
